baseURL = "https://nerdtech.live"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "NERD TECH"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "nerdtech-1"
googleAnalytics = "G-TDH2YR7B3P"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post", "posts"]
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength = "9"
gcse = false
Lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "Coding is my canvas, and technology is my masterpiece."
description = "NerdTech.live is a blog about technology, programming, and other cool stuff."


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[Author]
name = "Aryan Arora"
website = "https://stuckaryan.tech"
email = "aroraryan826@gmail.com"
# facebook = "username"
instagram = "am.aaryan_"
youtube = "channel/stuckaryan" # or channel/channelname
twitter = "am.aaryan"
threads = "username"
linkedin = "username"
github = "0aaryan"
#gitlab = "username"
#bitbucket = "username"
#reddit = "username"
#xing = "username"
#stackoverflow = "users/XXXXXXX/username"
#snapchat = "username"
#soundcloud = "username"
#spotify = "username"
#bandcamp = "username"
#itchio = "username"
#vk = "username"
#paypal = "username"
#telegram = "username"
#500px = "username"
#codepen = "username"
#mastodon = "url"
#kaggle = "username"
#weibo = "username"
#slack = "username"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

# [[menu.main]]
# name = "Notes"
# url = "/notes/"
# weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags/blog/"
# weight = 3

# [[menu.main]]
# name = "Collections"
# url = "/collections/"
# weight = 4

[[menu.main]]
name = "About"
url = "/about/"
weight = 5
